name: "Lint"
description: "Run all lint (pre-commit) checks"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"

    - name: Install Poetry
      uses: snok/install-poetry@v1.4.1

    - name: Install dependencies
      shell: bash
      run: |
        poetry install --all-groups

    - name: Validate Conventional Commits
      shell: bash
      if: ${{ github.ref != 'refs/heads/main' }}
      run: |
        poetry run cz check --rev-range origin/main..HEAD

    - name: Run lint
      shell: bash
      run: |
        poetry run poe lint
