name: Version Bump and Create a Release

on:
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  version-bump:
    name: 📦 Stable Release
    needs: ci
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          token: "${{ secrets.WORKFLOW_TOKEN }}"
          fetch-depth: 0

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd # v7
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_push_gpgsign: false

      - name: Remove canary dev tags
        run: git tag -l '*dev*' | xargs --no-run-if-empty git tag -d

      - name: Create bump and changelog
        uses: ./.github/actions/commitizen-bump
        with:
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
          gpg_sign: true

      - name: Build release notes
        uses: ./.github/actions/build-release-notes
        with:
          from_tag: "v${{ env.PREVIOUS_REVISION }}"
          to_tag: "v${{ env.REVISION }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          body_path: release-notes.md
          tag_name: "v${{ env.REVISION }}"
